### ISSUE TITLE
Initial load of studio_view does not have all checkboxes checked

### ISSUE THREAD

**Issue by ewall** [MEdXcognition/reflection#1]
The first time a course author opens the studio_view, we want all the checkboxes to default to be checked, as the corresponding Python fields default to true.

Hard-coding the "checked" attribute in HTML doesn't agree with JQuery's changing the checked property to true or false, they just stay permanently checked. Do we need to have JQuery remove the property when disabling?

Alternately, why doesn't refreshing the checked state from the default config check all the boxes for us, like it does correctly after the course author has saved changes at least once?

**Comment by maykristine** [comment]
I think we should remove the "checked" attribute in the HTML.

As for the refresh issue, does it occur after selecting the eval radio button?
I noticed some refresh issue on the xblock dev envt, but I was hoping it is just on that environment.
Does that mean the page reload actions are not redone after doing so?
I tried adding a refresh screen before, but it didn't stop refreshing then.

**Comment by ewall** [comment]
Current master branch has no "checked" attributes hard-coded in the HTML because of this.

I'll continue to work on it as time permits, but wanted to at least record it as a small issue to be resolved.

**Comment by ewall** [comment]
Resolved in 18f84f279f55fb7b0a217b64b5a2eb50d49bb2bd
