### ISSUE TITLE
Set friendly name on the XBlock header when viewed in edX Studio

### ISSUE THREAD

**Issue by ewall** [MEdXcognition/reflection#2]
When you add an instance of this XBlock to a course in edX Studio, the header/title of the block is some sort of unique instance ID, but we'd like it to be a friendly name like "Reflection Assistant".

![xblock header](https://user-images.githubusercontent.com/20837/28447316-063dfec8-6d9e-11e7-83cf-b76d4f55efa9.png)

**Comment by maykristine** [comment]
I was able to resolve this locally by adding display_name field on Python.
I think I have some other environment issues, though after merging my branch from master (or maybe after tinkering a lot with my devstack?).
<img width="907" alt="screen shot 2017-07-22 at 5 59 01" src="https://user-images.githubusercontent.com/9590206/28482350-eb8217bc-6ea2-11e7-9b69-4a17359aa0bf.png">

**Comment by ewall** [comment]
Resolved in 1de61c730807e798624039a1fbb931f3db861783
