### ISSUE TITLE
HTML5 validation concerns

### ISSUE THREAD

**Issue by ewall** [MEdXcognition/reflection#3]
Since a course would typically have more than one instance of this XBlock, each instance prefixes all the HTML 'id' attributes with a unique id so the JavaScript can target correctly. However, the HTML5 'name' attributes are used for the data gathering and often differ from the 'id' attributes on those tags. As I understand it, the HTML5 spec suggests that 'id' and 'name' values should be the same when both are present. Is this a concern?

**Comment by maykristine** [comment]
:o 
I didn't know about the id, name recommendation. :p
Anyway, during creation of JSON string, I am just getting the field name as the key.
I'd check out if we can find/define a different attribute that we can use so we can keep up with the HTML5 spec.

**Comment by ewall** [comment]
No worries. Browsers are more cooperative/resilient than the specs.

A possible is to create our own data attribute like 'data-disp' which JavaScript reads as element.dataset.disp / JQuery reads as element.data("disp").

Either way, it's not really high priority at this point, I don't think.

**Comment by ewall** [comment]
Resolved in 18f84f279f55fb7b0a217b64b5a2eb50d49bb2bd
