### ISSUE TITLE
Form submission fails in Prep phase student_view

### ISSUE THREAD

**Issue by ewall** [MEdXcognition/reflection#5]
In the student_view of the Preparation XBlock, submitting the form fails. There are no errors on the JavaScript side; it appears to be the Python side which is rejecting it.

**Comment by maykristine** [comment]
[d92a4de](https://github.com/MEdXcognition/reflection/commit/d92a4de20e3cf14cc52840a1419c7a6ea698ac89)

**Comment by ewall** [comment]
Turns out just adding "var" would tie the scope to the XBlock instance.

Same fixes applied to the studio_views in f1fdb30c977ddceb7f9add56167ddb03c9b85449
