### ISSUE TITLE
UI bug: misplaced form submission feedback

### ISSUE THREAD

**Issue by ewall** [MEdXcognition/reflection#6]
If you have multiple of these XBlocks on the same page (e.g. both the Preparation and Evaluation XBlocks), when you submit the form on the first one the feedback message (success or failure) appears with the last XBlock instead of the one you submitted from.

**Comment by maykristine** [comment]
I cannot seem to replicate this, though...

**Comment by ewall** [comment]
I suspect that's because you fixed it with d92a4de20e3cf14cc52840a1419c7a6ea698ac89 -- its longer trying to submit the wrong form. Darn JavaScript global namespace!

**Comment by ewall** [comment]
Confirmed -- fixing the scope of the $form variables resolves this properly. Added the same fix to the studio_views in f1fdb30c977ddceb7f9add56167ddb03c9b85449
